name: ✨ Feature Request
description: Suggest an idea or enhancement for SnappDesignTokens
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe the issue you're trying to solve.
      placeholder: I'm frustrated when... / It would be helpful if... / Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to be able to... / The library should... / Add support for...
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of SnappDesignTokens does this feature relate to?
      options:
        - DTCG Parsing
        - Token Types Support
        - Reference Resolution
        - Swift API Design
        - Performance
        - Error Handling
        - Documentation
        - Testing
        - Other (please specify below)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Critical for my use case
        - Urgent - Blocking my project
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help you.
      placeholder: In my app, I need to... / When working with design tokens, I want to... / This would help me...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... / Another approach could be... / Currently I work around this by...
    validations:
      required: false

  - type: textarea
    id: example-api
    attributes:
      label: Proposed API (Optional)
      description: If you have ideas about how the API should look, please share them here.
      placeholder: |
        ```swift
        // Example of how you envision using this feature
        let tokens = TokenParser()
        tokens.newFeature(...)
        ```
      render: swift
    validations:
      required: false

  - type: textarea
    id: dtcg-example
    attributes:
      label: DTCG Example (Optional)
      description: If this relates to DTCG token parsing, provide an example of the token structure.
      placeholder: |
        ```json
        {
          "example": {
            "token": {
              "$type": "...",
              "$value": "..."
            }
          }
        }
        ```
      render: json
    validations:
      required: false

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would implementing this feature require breaking changes to the current API?
      options:
        - "No, this can be added without breaking existing code"
        - "Yes, this would require breaking changes"
        - "I'm not sure"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, links to specifications, or examples that would help us understand your request.
      placeholder: Links to relevant documentation, similar features in other libraries, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Verification
      description: Please verify the following before submitting this feature request.
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have provided a clear description of the problem and proposed solution
          required: true
        - label: This feature aligns with the goals of SnappDesignTokens (DTCG parsing for Swift)
          required: true