 name: Package Test

 on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 jobs:
  coverage:
    uses: "oleksiikolomiietssnapp/swift-coverage-workflows/.github/workflows/swift-coverage.yml@main"
